version: '3.9'

services:
  db:
    container_name: poker_postgres_dev
    platform: linux/amd64 #for platform error on Apple M1 chips
    image: poker_postgres_dev
    build:
      context: .
      dockerfile: Dockerfile_Postgresql
    restart: always
    env_file: .env
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # if you want to use a bind folder
      # - strapi-data:/var/lib/postgresql/data/ #using a volume
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - poker-game-network

  be_tcp_app_dev:
    container_name: be_tcp_app_dev
    build:
      context: .
      dockerfile: ./be-tcp-app/Dockerfile
    restart: unless-stopped
    image: be_tcp_app_dev_image
    env_file: 
      - ./.env
    ports:
      - '3005:3000'
    depends_on:
      - db
      - redis
    networks:
      - poker-game-network
    volumes:
      - ./be-tcp-app:/app
    command: 'npm run start:dev'

  be_tcp_strapi_dev:
    container_name: be_tcp_strapi_dev
    image: naskio/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME:-pokeroyun}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-turkpokeradmin}
      DATABASE_PORT: ${DATABASE_PORT:-5434}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-turkpokeradmin}
      NODE_ENV: ${NODE_ENV} # production için production kullanılır
      APP_KEYS: ${APP_KEYS}
      # DATABASE_SSL: false
      # DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
    ports:
      - '1340:1337'
    volumes:
      - ./be-tcp-strapi:/srv/app
    networks:
      - poker-game-network
    links:
      - db
    depends_on:
      - db
    command: 'npm run develop'

  redis:
    container_name: redis_dev_db
    image: redis_dev_db_image
    build: ./redis
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PORT='6379'
    ports:
      - "6379:6379"
    networks:
      - poker-game-network
    restart: unless-stopped

networks:
  poker-game-network:
    name: poker-game-network
    driver: bridge

volumes:
  pgdata:
  redis-data:
