###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18.16-alpine As development

# Create app directory
WORKDIR /app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
# COPY --chown=node:node package*.json ./
COPY **/package.json ./
COPY **/package-lock.json ./

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci --omit=dev

# Bundle app source
# COPY --chown=node:node . .
COPY . .
COPY .env  ./
ENV NODE_ENV production
RUN npm run build

# Use the node user from the image (instead of the root user)
# USER node
CMD [ "node", "dist/main.js" ]
